# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  comiple:
    runs-on: Agent-1

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set UP nodejs
      uses: actions/setup-node@v4
      with:
        node-version: '23'
         
